
version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: "sqltools-mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_dbdata:/var/lib/postgresql/data
  postgres:
    image: "postgres:12-alpine"
    container_name: "sqltools-postgres"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=sampledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_dbdata:/var/lib/postgresql/data
volumes:
  postgres_dbdata:
  mysql_dbdata:

